### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by evaporei**
Depends on https://github.com/edn-rs/edn-rs/pull/130 **and** a new version released.

### CODE REVIEW

**Comment by Grinkers** [comment]
@evaporei 

Rebased and now pointing directly to `git/main` for now. There's likely going to be at least a couple breaking changes I want to introduce, so we can just have it like this until the breaking changes are done and @naomijub is back to plan releases in Feb

**Comment by evaporei** [comment]
Alrighty, I still need a review to merge tho.

**Review by Grinkers — APPROVED** [review]

**Comment by Grinkers** [comment]
> Alrighty, I still need a review to merge tho.

Actually I think it's you. I'm the last to push here. Or at least hopefully this doesn't mean a 3rd is required.

**Comment by evaporei** [comment]
> Actually I think it's you. I'm the last to push here. Or at least hopefully this doesn't mean a 3rd is required.

Unfortunately I can't approve my own PR:



And yes you're correct, you can't approve because you were the last one to push:



I'm thinking a bit if there's another way other than closing this PR and creating a new one.

**Comment by evaporei** [comment]
I think in those scenarios is better to request changes instead of changing it yourself.

**Comment by Grinkers** [comment]
> I think in these scenarios it's better to request changes instead of changing it yourself.

Huh, that's pretty weird. What if two people want to both contribute to one thing, then it ends up deadlocked? It makes way more sense to have the last commit require a review by somebody else...

Well feel free to rewrite history (rebase and delete my commit and author it yourself). My intention was to just quickly do it, after approving edn-rs main's PR, so all you had to do was click a button.

**Comment by Grinkers** [comment]
@evaporei I removed the commit, I'll let you do the last one with
`edn-rs = { git = "https://github.com/edn-rs/edn-rs.git" } # TODO lock in version once ` while we sort out the circular dependencies?

**Pull request merged**
